name: Sync to Gitee including Wiki

on:
  push:
    branches:
      - main  # 或者是你想要同步的分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.email "18512872230@163.com"
        git config --global user.name "xiaohajiayou"

    - name: Print GITEE_REPO
      run: echo "GITEE_REPO=${{ secrets.GITEE_REPO }}"

    - name: Add Gitee remote
      run: |
        git remote add gitee https://lilhah:${{ secrets.GITEE_TOKEN }}@gitee.com/lilhah/easy-markdown-migrate.git

    - name: Fetch all remotes
      run: |
        git fetch --all

    - name: Push to Gitee
      run: |
        git push gitee HEAD:main --force

    - name: Checkout Wiki
      run: |
        git clone https://github.com/${{ github.repository }}.wiki.git wiki

    - name: Add Gitee Wiki remote
      run: |
        cd wiki
        git remote add gitee-wiki https://lilhah:${{ secrets.GITEE_TOKEN }}@gitee.com/lilhah/easy-markdown-migrate.wiki.git

    - name: Fetch all Wiki remotes
      run: |
        cd wiki
        git fetch --all

    - name: Reset Wiki Git repository
      run: |
        cd wiki
        git reset --hard
        git clean -fd

    - name: Push Wiki to Gitee
      run: |
        cd wiki
        git push gitee-wiki HEAD:master --force